# Generated by Django 4.2.9 on 2024-02-03 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=255, unique=True)),
                ('unique_uuid', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=255, unique=True)),
                ('main_text', models.TextField()),
                ('data', models.JSONField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hack.author')),
            ],
        ),
    ]
