# Generated by Django 4.2.9 on 2024-02-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0003_socialcontent_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_fetched',
            field=models.BooleanField(default=False),
        ),
    ]
