# Generated by Django 4.2.9 on 2024-02-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0005_socialcontent_comments_socialcontent_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('user_profile_url', models.URLField()),
                ('image_link', models.URLField()),
            ],
        ),
    ]
