# Generated by Django 4.2.9 on 2024-02-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0007_instagram_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram',
            name='image_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='user_profile_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
